### ISSUE TITLE
getInfo is not a function

### ISSUE THREAD

**Issue by deniscerri** [zackradisic/node-soundcloud-downloader#44]
I am updated to the latest version. Tried another soundcloud id. The url is correct. Help

**Comment by zackradisic** [comment]
Please post the error log so I can diagnose what the issue is.

**Comment by deniscerri** [comment]
Server is working at port: 3000
https://soundcloud.com/cj50058/whoopty-1
TypeError: scdl.getInfo is not a function
    at C:\Users\denis\Desktop\Testing Programs\ytdl\lib\soundcloud.js:16:29
    at Layer.handle [as handle_request] (C:\Users\denis\Desktop\Testing Programs\ytdl\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\denis\Desktop\Testing Programs\ytdl\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\denis\Desktop\Testing Programs\ytdl\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\denis\Desktop\Testing Programs\ytdl\node_modules\express\lib\router\layer.js:95:5) 
    at C:\Users\denis\Desktop\Testing Programs\ytdl\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\denis\Desktop\Testing Programs\ytdl\node_modules\express\lib\router\index.js:335:12)        
    at next (C:\Users\denis\Desktop\Testing Programs\ytdl\node_modules\express\lib\router\index.js:275:10)
    at expressInit (C:\Users\denis\Desktop\Testing Programs\ytdl\node_modules\express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (C:\Users\denis\Desktop\Testing Programs\ytdl\node_modules\express\lib\router\layer.js:95:5)
